In [17]:
import numpy as np
#ВАРИАНТ 8
# Функция для проверки транспонированной суммы двух матриц
def check_transpose_sum(A, B):
    return np.transpose(A + B) == np.transpose(A) + np.transpose(B)

# Функция для умножения матриц
def matrix_product(A, B):
    return np.dot(A, B)

# Функция для нахождения определителя по методу Саррюса
def sarus_determinant(A):
    return (A[0, 0] * A[1, 1] * A[2, 2] + A[0, 1] * A[1, 2] * A[2, 0] +
            A[0, 2] * A[1, 0] * A[2, 1] -
            A[0, 2] * A[1, 1] * A[2, 0] - A[0, 1] * A[1, 0] * A[2, 2] -
            A[0, 0] * A[1, 2] * A[2, 1])
# Проверка A * A^(-1) = E
def check_inverse_identity(A, A_inv):
    return np.allclose(np.dot(A, A_inv), np.eye(A.shape[0]))
# Заданные матрицы
A1 = np.array([[6, -3, -1], [-4, -2, -1], [5, 0, 6]])
B1 = np.array([[-3, 1, 0], [-2, 7, 2], [5, -5, 5]])
I = np.eye(3)  # Единичная матрица размером 3

A2 = np.array([[-3, 0, -4], [-2, -4, -2], [2, -2, -1]])
B2 = np.array([[0, -5, 6], [2, 0, 6], [-1, 5, -4]])

A3 = np.array([[-4, 7, -5], [1, -4, 7], [0, -4, 3]])
B3 = np.array([[7, 3], [2, 2], [2, -1]])

# Для выполнения 4.3 я немного схитрил и воспользовался документацией питона, где "локанично" реализован метод поиска союзной матрицы
#  (у меня не возникло бы проблемы сделать это в экселе, но раз уж начал писать код, то закончу) 


# Функция для нахождения определителя матрицы произвольного размера (прошлая формула не подходит, тк будут определители 2на2)
def determinant(matrix):
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Определитель можно вычислить только для квадратных матриц.")
        
    # Используем `numpy` для нахождения определителя
    return np.linalg.det(matrix)

# Функция для нахождения алгебраического дополнения
def cofactor_matrix(matrix):
    n = matrix.shape[0]
    cofactors = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            # Создаем подматрицу (удаляем i-ю строку и j-ю колонку)
            sub_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            # Вычисляем определитель подматрицы
            cofactors[i, j] = ((-1) ** (i + j)) * determinant(sub_matrix)
    return cofactors

# Функция для нахождения обратной матрицы
def inverse_matrix(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Обратной матрицы не существует (определитель равен 0).")
    
    cofactors = cofactor_matrix(matrix)
    # Транспонируем матрицу кофакторов 
    adjugate = cofactors.T
    # Соотношение для нахождения обратной матрицы
    return adjugate / det

# Заданная матрица A4
A4 = np.array([[-2, -5, -1],
                [1, 0, 7],
                [2, -4, 6]])
#--------------------------------------------------------------------------------------

# 1. Проверка для транспонированной суммы
print("1. Проверка для транспонированной суммы:\n", check_transpose_sum(A1, B1))

# 2. -5A + 2В
result = -5 * A2 + 2 * B2
print("2. -5A + 2B:\n", result)

# 3. Умножение двух матриц
product_result = matrix_product(A3, B3)
print("3. Произведение двух матриц:\n", product_result)

# 4.1 Нахождение определителя
det_sarus = sarus_determinant(A4)
print("4.1 Определитель матрицы A по методу Саррюса:", det_sarus)

# 4.3 найти обратную матрицу при помощи союзной
try:
    cofactors_A4 = cofactor_matrix(A4)
    inv_A4 = inverse_matrix(A4)
    print("4.3 найти обратную матрицу при помощи союзной:")
    print("*Союзная матрица:*")
    print(cofactors_A4.T)  # Транспонируем для получения союзной
    print("Обратная матрица:")
    print(inv_A4)
except ValueError as e:
    print("\n**Ошибка:**", str(e))

# 4.4 Проверка на обратную матрицу
inverse_check = check_inverse_identity(A4, inv_A4)
print("4.4 Проверка A * A^(-1) = E:", inverse_check)

#5. Найти обратную матрицу способом разбиения на клетки
def split_matrix(matrix):
    # Проверяем, что матрица 4x4
    if matrix.shape != (4, 4):
        raise ValueError("Матрица должна быть 4x4")
    
    # Разделяем на блоки 2x2
    a_11 = matrix[0:2, 0:2]
    a_12 = matrix[0:2, 2:4]
    a_21 = matrix[2:4, 0:2]
    a_22 = matrix[2:4, 2:4]
    
    return a_11, a_12, a_21, a_22


# Создаем матрицу 4x4
matrix = np.array([
        [4, 1, 0, 1],
        [-1, 5, 1, 4],
        [5, -3, -5, -5],
        [-2, 3, 4, -4]
])
    
    # Разделяем матрицу на блоки 2x2 и присваиваем их отдельным переменным
a_11, a_12, a_21, a_22 = split_matrix(matrix)

    # Находим необходимые матрицы и формулы
a_11_inv = np.linalg.inv(a_11)
    
    # Вычисляем Y и Q
Y = a_21 @ a_11_inv
Q = a_22 - Y @ a_12

Q_inv = np.linalg.inv(Q)

        # Вычисляем блоки x
x_11 = a_11_inv + a_11_inv @ a_12 @ Q_inv @ Y
x_12 = -a_11_inv @ a_12 @ Q_inv
x_21 = -Q_inv @ Y
x_22 = Q_inv

        # Сборка полной обратной матрицы из блоков
inv_matrix = np.block([[x_11, x_12],
                                [x_21, x_22]])
        
print("5. Обратная матрица способом разбиения на клетки:")
print(inv_matrix)
nverse_check = check_inverse_identity(matrix, inv_matrix) # Сделал проверку для убидительности 
print("5 Проверка A * A^(-1) = E:", inverse_check)

1. Проверка для транспонированной суммы:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
2. -5A + 2B:
 [[ 15 -10  32]
 [ 14  20  22]
 [-12  20  -3]]
3. Произведение двух матриц:
 [[-24   7]
 [ 13 -12]
 [ -2 -11]]
4.1 Определитель матрицы A по методу Саррюса: -92
4.3 найти обратную матрицу при помощи союзной:
*Союзная матрица:*
[[ 28.  34. -35.]
 [  8. -10.  13.]
 [ -4. -18.   5.]]
Обратная матрица:
[[-0.30434783 -0.36956522  0.38043478]
 [-0.08695652  0.10869565 -0.14130435]
 [ 0.04347826  0.19565217 -0.05434783]]
4.4 Проверка A * A^(-1) = E: True
5. Обратная матрица способом разбиения на клетки:
[[ 0.24535809 -0.05702918 -0.00397878  0.00928382]
 [-0.0397878   0.22546419  0.10875332  0.0795756 ]
 [ 0.21087533 -0.19496021 -0.17639257  0.07824934]
 [ 0.05835544  0.00265252 -0.0928382  -0.11671088]]
5 Проверка A * A^(-1) = E: True
